team-da-sh/dash-client

- package.json
- pnpm-lock.yaml
- close #11 
package.json 오류 수정
> [fix] package.json 오류 수정 

- README.md
- close #13 
프로젝트 1차 readme 작성
> [docs] 프로젝트 1차 readme 작성

- README.md
- eslint.config.js
- package.json
- src/App.tsx
- src/components/Button/index.css.ts
- src/components/Button/index.tsx
- src/components/ButtonStory/Button.tsx
- src/components/Card/index.css.ts
- src/components/Card/index.tsx
- src/queryClient.ts
- src/stories/Button.stories.tsx
- src/styles/global.css.ts
- src/styles/index.css.ts
- src/styles/reset.css.ts
- src/styles/theme.css.ts
- tsconfig.json
- vite.config.ts
- close #16  
```typescript
import { recipe } from '@vanilla-extract/recipes';
import { vars } from '../../styles/theme.css';
export const button = recipe({
base: {
backgroundColor: vars.colors.black,
color: vars.colors.white,
...vars.fonts.body02_smbold,
borderRadius: '10px',
border: 'none',
},
variants: {
size: {
sm: {
padding: '0.5rem',
},
md: {
padding: '1rem',
},
lg: {
padding: '1.5rem',
},
},
},
});
```
1. `theme` 사용 시, `theme` 파일에서 정의한 `vars`를 `import` 해서 사용하면 됩니다.
2. font의 경우에는 `...vars.fonts.body02_smbold`와 같이 사용하시면 됩니다.
> [setting] Theme 세팅

- package.json
- pnpm-lock.yaml
- src/components/Header/index.css.ts
- src/components/Header/index.tsx
- close #46  
package.json 파일 쉼표 추가해주어서 오류 해결하였습니다.
Header 컴포넌트 절대경로로 수정 후, 폰트 Head 컴포넌트로 사용하도록 수정완료 했습니다.
> [Fix] package.json 파일 오류 해결

- src/components/Header/index.css.ts
- src/components/Header/index.tsx
- close #51  
레시피를 활용하여 `headerRootStyle`에 `variants`를 정의하여 `isColor` 값에 따라 `background-color`가 유동적으로 변경될 수 있도록 하였습니다.
```typescript
<Header.Root isColor={true}>
<Header.BackIcon onClick={handleBackClick} />
<Header.Title title="강사등록" />
<Header.CloseIcon onClick={handleCloseClick} />
</Header.Root>
```
Header.Root에 isColor={true}를 줄시 background가 흰색, isColor={false}일시 투명색입니다.
> [Fix] Header 공통 컴포넌트 스타일 수정

- src/components/Input/index.css.ts
- src/components/Input/index.tsx
- close #35 
Input 공통 컴포넌트를 구현한다.
- Props에서 `isError`만 두고 border css를 분기 처리하였습니다. 그래서 사용하시는 페이지(컴포넌트)에서 
```ts
const [isError, setIsError] = useState<boolean>();
const [errorMsg, setErrorMsg] = useState('');
```
해당 예시와 같이 Error의 유무 상태와 에러 메시지 상태를 관리하여 Input 공통 컴포넌트에 `isError`값으로 넘겨주시면 됩니다!
추후에 필요하다면 Error message도 공통 컴포넌트에 추가하도록 하겠습니다!
**[예시 코드]**
```ts
import { ChangeEvent, useState } from 'react';
import Input from '@/components/Input';
const Login = () => {
const [name, setName] = useState('');
const [isError, setIsError] = useState<boolean>();
const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
const value = e.target.value;
setName(e.target.value);
if (value.length > 4) {
setIsError(true);
return;
}
setIsError(false);
};
return (
<>
<Input onChange={handleChange} …
```
> [Feat] Input 공통 컴포넌트 구현

- .storybook/preview.ts
- src/App.tsx
- src/components/BoxButton/index.css.ts
- src/components/BoxButton/index.tsx
- src/components/Button/index.css.ts
- src/components/Button/index.tsx
- src/stories/BoxButton.stories.tsx
- src/stories/Button.stories.tsx
- src/stories/ButtonStory.stories.tsx
- src/styles/theme.css.ts
- close #24
BoxButton 공통 컴포넌트를 구현했습니다! 
원래 Button 으로 하려고 했는데 생각보다 버튼으 종류가 애매하게 나눠져있어서 일단 Box 형태의 기본적인 버튼을 구현했습니다. 
내일 작업시작하면서 버튼으로 더 분리할 것들이 있으면 더 구현해보겠습니다!
variant 값에 따라서 버튼의 style을 주입해주었습니다.
disabled는 isDisabled prop으로 넘겨주면 됩니다!
variant에 알맞은 값 주고 isDisabled에 활성화, 비활성화 boolean값 넘겨주면 끝입니다~
```typescirpt
<BoxButton variant="primary" isDisabled={true}>
버튼
</BoxButton>
```
> [Feat] BoxButton 공통 컴포넌트 구현

- src/components/ProgressBar/index.css.ts
- src/components/ProgressBar/index.tsx
- src/stories/ProgressBar.stories.tsx
- close #20 
```typescript
const ProgressBar = ({ totalStep, currentStep }: ProgressBarProps) => {
return (
<div className={styles.progressBarWrapperStyle}>
{[...Array(totalStep)].map((_, index) => {
const isActive = index + 1 === Math.min(currentStep, totalStep);
return <div key={index} className={styles.progressBarSegmentStyle({ isActive })} />;
})}
</div>
);
};
export default ProgressBar;
```
`Math.min(currentStep, totalStep)`는 `currentStep`이 `+1`씩 되더라도 `totalStep`을 초과하지 못하도록 하기위하여 `Math`함수를 사용했습니다. 더 좋은 의견있면 의견 부탁드려요.
```typescript
<ProgressBar totalStep={5} currentStep={currentStep} />
```
`totalStep`에는 총`step`의 갯수, `currentStep`은 화면에 보여지는 `step`에 따라서 유동적으로 변경되도록 하면 됩니다.(다음 버튼을 클릭하면 currentStep + 1 되도록, 초기값은 1)
**totalStep = 5인 경우** …
> [Feat] ProgressBar 공통 컴포넌트 구현

- package.json
- pnpm-lock.yaml
- src/pages/search/Calendar/index.css.ts
- src/pages/search/Calendar/index.tsx
- close #48
[https://github.com/wojtekmaj/react-calendar/blob/main/packages/react-calendar/src/Calendar.tsx](url)
[https://github.com/wojtekmaj/react-calendar/blob/main/packages/react-calendar/src/Calendar.css](url)
위의 공식문서를 참고하면서, `CSS`만질때는 개발자 모드 켜놓고 `className`마다 어떤 요소를 꾸미는 건지 확인하면서 작업했습니다. 생각보다 css가 적용안되는 것들이 많아서 많이 애먹었네요.
이해하기에 난해해 보이는 코드들이 많은데, 궁금하신 부분은 물어봐주세요!
```typescript
console.log(startDate); // 시작 날짜
console.log(endDate); // 끝 날짜
```
해당 콘솔은 추후 api 연결할 때 사용되는 `startDate`와 `endDate`인데, eslint에서 노란줄이 떠서 임의로 콘솔로 찍어두었습니다.
https://github.com/user-attachments/assets/3d43f465-494f-49e0-afa7-e1ab74c12010
https://github.com/user-attachments/assets/8dd53c4c-4dc4-42b6-961d-255a8a292771
[https://mj001027.tistory.com/22](url)
위의 블로그에 저희 캘린더 디자인과 비슷하게 커스텀한 내용이 있어서 참고하여 작업했습니다.
디자이너 선생님들께 확인 …
> [Feat] 캘린더 커스텀

- src/components/Completion/index.css.ts
- src/components/Completion/index.tsx
- src/pages/instructorRegister/CareerStep/index.css.ts
- src/pages/instructorRegister/CareerStep/index.tsx
- src/pages/instructorRegister/CompletionStep/index.tsx
- src/pages/instructorRegister/Description/index.tsx
- src/pages/instructorRegister/IntroductionStep/index.css.ts
- src/pages/instructorRegister/IntroductionStep/index.tsx
- src/pages/instructorRegister/PersonalSNSStep/index.css.ts
- src/pages/instructorRegister/PersonalSNSStep/index.tsx
- src/pages/instructorRegister/VideoLinkStep/index.css.ts
- src/pages/instructorRegister/VideoLinkStep/index.tsx
- src/pages/instructorRegister/index.tsx
- close #114 
강사 등록 Funnel에서 영상 업로드/소개글 작성 Step을 퍼블리싱하였습니다.
- 소개 글을 작성하는 `TextArea`에서 단순하게 영역을 주고 스크롤이 되는 것이 아닌 피그마 상으로 기본 Default 높이가 있고 입력하는 값이 많아져서 줄바꿈이 되면 될수록 height 값이 길어져야 했습니다. 이 부분을 저는 `TextArea`를 `useRef`로 지정하고 기존 `style.height` 값을 **5.4rem**을 주었습니다. 이후 `textArea.scrollHeight`가 바뀌면 이에 따라 높이가 자동으로 변경되도록 구현하였습니다.
**[해당 코드]**
```ts
const textAreaRef = useRef<HTMLTextAreaElement>(null);
const handleInput = () => {
const textArea = textAreaRef.current;
if (textArea) {
textArea.style.height = '5.4rem'; // Default 높이!
textArea.style.height = `${textArea.scrollHeight}px`; // 내용에 따라 높이 조정
}
};
return (
<>
<Description title="소개글 작성" subTitle="댄서 메인테인 님에 대해 30자 이상 작성해 주세요" />
<textarea
ref={textAreaRef}
onInput={handleInput}
placeholder="저는 이런 댄서예요!"
className={textAreaStyle}></textarea> …
```
> [Feat] 강사 등록 영상 업로드/소개글 작성 Step 퍼블리싱

- src/pages/instructor/classDetail/StudentCard/index.css.ts
- src/pages/instructor/classDetail/StudentCard/index.tsx
- src/pages/instructor/classDetail/index.css.ts
- src/pages/instructor/classDetail/index.tsx
- src/pages/instructor/classDetail/mocks/mockLessonDetail.ts
- src/pages/mypage/TopSection/index.tsx
- src/utils/timeCalculate.ts
- close #119 
- 강사가 본인이 개설한 클래스 목록에서 상세보기를 클릭했을 시 나오는 페이지를 완성했습니다.
- API 반환 값 사용해서 작성했습니다. 거의 단순 퍼블리싱 입니닷
- classDetail 페이지에는 공통컴포넌트인 classCard와 신청한 학생 목록을 카드로 렌더링할 studentCard가 존재합니다.
> [Feat] 내 클래스 목록 상세 페이지

- src/hooks/useClickOutside.ts
- src/hooks/useOutsideClick.ts
- src/pages/search/components/TabContainer/TagSection/Dropdown/index.css.ts
- src/pages/search/components/TabContainer/TagSection/Dropdown/index.tsx
- src/pages/search/components/TabContainer/TagSection/index.tsx
- src/pages/search/components/TabContainer/index.css.ts
- src/pages/search/components/TabContainer/index.tsx
- close #139 
- Root: 드롭 다운 기본 동작을 위한 context를 내려주는 루트 컴포넌트 입니다. Dropdown 컴포넌트는 항상 Root 내에서 사용되어야 해요
- Trigger: 드롭 다운 메뉴를 열고 닫을 수 있는 `Trigger` 역할을 하는 컴포넌트 입니다. 드롭다운 메뉴를 열기 위한 요소에 감싸서 적용하면 됩니다.
- Content: 드롭 다운 메뉴의 리스트의 부모역할을 하는 컴포넌트 입니다.
- Item: 드롭 다운 메뉴의 리스트 아이템 컴포넌트 입니다. (선택적으로 사용가능합니다)
dropdown의 기본동작을 위한 context를 정의해요.
기본적으로 열고 닫는 동작을 해야되고, 내부 컴포넌트가 열고닫는 상태에 접근할수 있어야하기 때문에 context를 만들어 하위 컴포넌트가 사용할수있게 해야했어요.
```typescript
const DropdownContext = createContext<DropdownContextProps | null>(null);
const useDropdownContext = () => {
const context = useContext(DropdownContext);
if (!context) {
throw new Error('Select 컴포넌트는 Select.Root 내에서 사용되어야 합니다.');
}
return context;
};
```
<br>
```typescript
const DropdownRoot = ({ children }: DropdownRootProps) => {
const [open, setOpen] = …
```
> [Feat] 탐색 페이지 드롭다운 구현

- src/components/BoxButton/index.css.ts
- src/components/Header/index.css.ts
- src/components/Input/index.tsx
- src/pages/search/index.tsx
- close #149 
- input 공통 컴포넌트에서 isSearch Variant를 받는 코드가 삭제되어 있어서 추가해주었습니다.
- Header 공통 컴포넌트에 zIndex를 추가해주었습니다.
- 탐색페이지에서 사용하는 Header 컴포넌트에 isColor={true} 적용해주었습니다.
> [Fix] input 공통 컴포넌트 수정

- src/constants/regex.ts
- src/pages/instructor/classRegister/ClassAmount/index.css.ts
- src/pages/instructor/classRegister/ClassAmount/index.tsx
- src/pages/instructor/classRegister/ClassDescription/index.css.ts
- src/pages/instructor/classRegister/ClassDescription/index.tsx
- src/pages/instructor/classRegister/ClassGenre/index.css.ts
- src/pages/instructor/classRegister/ClassGenre/index.tsx
- src/pages/instructor/classRegister/ClassLevel/index.tsx
- src/pages/instructor/classRegister/ClassName/index.css.ts
- src/pages/instructor/classRegister/ClassName/index.tsx
- src/pages/instructor/classRegister/ClassPersonnel/index.css.ts
- src/pages/instructor/classRegister/ClassPersonnel/index.tsx
- src/pages/instructor/classRegister/ClassPlace/index.css.ts
- src/pages/instructor/classRegister/ClassPlace/index.tsx
- src/pages/instructor/classRegister/ClassRecommend/index.css.ts
- src/pages/instructor/classRegister/ClassRecommend/index.tsx
- src/pages/instructor/classRegister/ClassRepresentImage/index.tsx
- src/pages/instructor/classRegister/ClassSchedule/index.css.ts
- src/pages/instructor/classRegister/ClassSchedule/index.tsx
- src/pages/instructor/classRegister/Description/index.css.ts
- src/pages/instructor/classRegister/Description/index.tsx
- src/pages/instructor/classRegister/hooks/useClassRegisterForm.ts
- src/pages/instructor/classRegister/index.css.ts
- src/pages/instructor/classRegister/index.tsx
- close #142  
클래스 등록 페이지 퍼블리싱 및 상태 관리 로직 구현을 모두 작성하였습니다.
이슈는 퍼블리싱만 넣어두기는 했지만 하면서 상태 관리 로직을 먼저 설계하고 짜는 것이 중요하다고 판단해서 같이 하게 되었습니다!
wait~~~ 추가할 예정.....................
> [Feat] 클래스 등록 페이지 퍼블리싱 및 상태 관리 로직 구현

- src/pages/home/components/HomeHeader/index.css.ts
- src/pages/reservation/TopInfoContent/index.css.ts
- src/pages/reservation/index.css.ts
- src/pages/search/components/TabContainer/TagSection/BottomSheet/index.css.ts
- src/styles/theme.css.ts
- close #157 
theme.ts에 zindex 관련 설정 추가했습니다.
zindex 사용되는 파일 vars.zIndex.one,  two , ...로 수정했습니다!
```ts
zIndex: {
one: '1',
two: '2',
three: '3',
four: '4',
five: '5',
},
```
**홈 헤더는 zIndex two로 설정되어있습니다!!**
> [Feat] zIndex theme으로 수정

- src/pages/search/components/TabContainer/TagSection/BottomSheet/index.css.ts
- src/routes/routesConfig.ts
- close #164 
- 탐색페이지 바텀시트 zIndex 변경
- instructorClassList path 변경
> [Design] 탐색페이지 바텀시트 zIndex 수정

- src/components/Completion/index.css.ts
- src/components/Completion/index.tsx
- src/components/Input/index.tsx
- src/pages/instructorRegister/InstructorRegisterFunnel/CareerStep/InputSection/index.tsx
- src/pages/instructorRegister/InstructorRegisterFunnel/CareerStep/index.css.ts
- src/pages/instructorRegister/InstructorRegisterFunnel/CareerStep/index.tsx
- src/pages/instructorRegister/InstructorRegisterFunnel/IntroductionStep/index.tsx
- src/pages/instructorRegister/InstructorRegisterFunnel/PersonalSNSStep/index.tsx
- src/pages/instructorRegister/InstructorRegisterFunnel/VideoLinkStep/index.css.ts
- src/pages/instructorRegister/InstructorRegisterFunnel/VideoLinkStep/index.tsx
- src/pages/instructorRegister/InstructorRegisterFunnel/index.css.ts
- src/pages/instructorRegister/InstructorRegisterFunnel/index.tsx
- src/pages/instructorRegister/constants/index.ts
- src/pages/instructorRegister/index.tsx
- src/pages/instructorRegister/types/index.ts
- close #163 
강사 등록 페이지 유효성 검사 & form을 관리하는 로직을 구현하였습니다!!
- 퍼널 구조의 데이터 상태에 대한 고민을 해봤는데 다음과 같습니다.
1. step별로 각각 state로 관리하기
2. 하나의 state에 객체 형태로 데이터 관리하기
둘 중에 저는 2번째를 방법을 선택했습니다. 이유는 Funnel에서 step으로 상태들이 나눠진다고 생각할 수 있지만 결국 서버에 제출하는 데이터는 크게 하나로 묶어져 있고, Funnel 구조의 한 페이지 안에 있는 데이터들이라 종속, 연결 관계가 있다고 생각했기 때문입니다.
따라서 
```ts
const [info, setInfo] = useState({
imageUrl: '',
instagram: '',
youtube: '',
education: [''],
experience: [''],
detail: '',
videoUrls: [''],
});
```
로 하나의 state를 두고 key값으로 여러 step별 데이터를 구분하여 관리하는 방법을 선택했습니다.
**(팀원 규홍님의 코드를 참고하여 구현하였습니다)**
퍼널 구조상 step은 따로 관리하지만 다음 버튼은 한번에 공통으로 관리하기 때문에 버튼이 활성화 되는 기준이 다 다른 것을 분기 처리해줘야 했습니다.
이를 팀원 규홍님의 구조를 참고해 step별 가독성을 높이기 위해 `switch-case`문을 사용하여 버튼이 활성화 되는 기준을 따로 적어주었습니다. 
```ts
const buttonActive = (currentStep: number) => {
switch …
```
> [Feat] 강사 등록 페이지 유효성 검사 & form 관리 로직 구현

- src/apis/instructor/classRegister/queries/index.ts
- src/pages/instructor/classRegister/components/ClassSchedule/ClassRegisterBottomSheet/index.tsx
- src/utils/timeUtils.ts
- close #245 
클래스 등록 페이지 hotfix 이슈 해결 
- 버튼 활/비활성화 버그 수정
- times 데이터 안 들어오는 버그 수정
> [!HOTFIX] 클래스 등록 페이지 hotfix 이슈 해결 

- src/pages/home/components/BottomSection/index.tsx
- src/pages/home/components/TopSection/index.css.ts
- src/pages/home/components/TopSection/index.tsx
- src/pages/mypage/constants/myPageList.ts
- close #246 
- 마이페이지 경로 모두 연결
- 프로필 이미지 고정
> [!HOTFIX] 마이페이지 라우트 경로 설정 (#246)

- src/pages/search/components/TabContainer/index.tsx
- src/pages/search/index.tsx
> [Fix] 웹 QA(검색페이지)

- src/components/LevelButton/index.css.ts
- src/pages/home/components/DancerItem/index.css.ts
- src/pages/home/components/LessonItem/index.css.ts
- src/pages/home/components/LessonItem/newIndex.css.ts
- src/pages/login/components/KakaoButton/index.css.ts
- src/pages/login/components/KakaoButton/index.tsx
- src/pages/login/components/LoginHeader/index.tsx
- src/pages/onboarding/components/LevelStep/index.tsx
- src/pages/onboarding/components/OnboardingFunnel/index.tsx
- src/pages/onboarding/components/ProfileStep/index.tsx
- src/pages/search/components/TabContainer/DancerList/index.css.ts
> [Fix] 웹 QA 이슈 정리

- src/pages/auth/index.ts
> [HOTFIX] redirect url 수정 

- src/pages/instructor/classRegister/components/ClassSchedule/TimeStep/TimeControl/index.css.ts
- src/pages/instructor/classRegister/components/ClassSchedule/TimeStep/TimeControl/index.tsx
- src/pages/instructor/classRegister/components/ClassSchedule/TimeStep/index.tsx
- close #252 
- TimeSelector가 반응형에서 화면 비율이 줄어들었을때 화면이 깨지는 현상을 수정했습니다.
- 패딩이 두번 사용이 되어 있었고, 부모요소의 100%를 주고 자식도 100%를 줘서 수정했습니다
> [Design] timeSelector 수정 

- src/pages/auth/index.ts
- src/pages/login/components/KakaoButton/index.tsx
> fix: 수정 (#262)

- src/pages/auth/index.ts
- src/pages/login/components/KakaoButton/index.tsx
X
기획/디자인 QA용 2차 배포
- `redirect URL` 에서 `www` 제거
> 기획/디자인 QA용 2차 배포

- vercel.json
> [Deploy] vercel.json 파일 추가

- src/pages/instructor/classRegister/hooks/useClassRegisterForm.ts
- src/styles/font.css
- src/styles/theme.css.ts
- src/utils/timeUtils.ts
- close #269 
Pretendard 글꼴 설정 누락 및 타임 함수 오류 수정 
폰트 설정을 @import로 하고 fontface 설정, fontfamily 설정을 지웠습니다.
타임 함수에서 toISOstring으로 변환할시 자꾸 표준 시간으로 변환되어서 적용하지 않고 한국 시간. 설정한 시간으로 보내게 수정했습니다.
> [Fix] Pretendard 글꼴 설정 누락 및 타임 함수 오류 수정 

- src/components/Toast/index.tsx
- src/pages/home/components/BottomSection/index.tsx
- src/pages/home/components/TopSection/index.tsx
- src/pages/mypage/constants/myPageList.ts
- close #273 
- 토스트가 중복으로 쌓이는 현상 -> `toast.dismiss();`로 해결!!
- 마이페이지 내 추구예 기능 모두 토스트 추가
> [Feat] 토스트 중복 쌓임 해결 및 추가

- src/components/Tab/TabList.tsx
- src/pages/search/components/Calendar/index.css.ts
- src/pages/search/components/TabContainer/TagSection/BottomSheet/index.css.ts
- src/pages/search/components/TabContainer/TagSection/BottomSheet/index.tsx
- src/pages/search/components/TabContainer/TagSection/index.css.ts
- src/pages/search/index.css.ts
- close #275
탐색페이지 QA 디자인 자잘한 수정사항 반영했습니다.
> [Fix] 전체 QA (탐색페이지)

- src/components/LevelButton/index.css.ts
- src/components/LevelButton/index.tsx
- src/components/Tag/index.css.ts
- src/pages/search/components/TabContainer/TagSection/index.css.ts
> [Fix] 자잘한 수정사항 반영

- src/pages/home/components/BottomSection/index.tsx
- src/pages/home/components/TopSection/index.tsx
- src/pages/mypage/mypageReservation/index.tsx
> [Fix] 마이페이지 오류 수정

- src/pages/mypage/constants/myPageList.ts
> [Fix] 마이페이지 클릭시 토스트 나타나는 현상 해결 

- src/pages/instructorRegister/components/InstructorRegisterFunnel/CareerStep/InputSection/index.tsx
- src/pages/instructorRegister/components/InstructorRegisterFunnel/IntroductionStep/index.tsx
- src/pages/instructorRegister/components/InstructorRegisterFunnel/PersonalSNSStep/index.tsx
- close #291 
전체 QA 버그 수정 (댄서 네임, input value 지정)
> [!HOTFIX] 전체 QA 버그 수정 (댄서 네임, input value 지정)

- src/apis/auth/quries/index.ts
- close #296 
로그인과 온보딩 그 사이 버뮤다 삼각지대에서 로컬스토리지를 한번 싹 비워줌으로 버그사항을 하나 해결했습니다.
> [Fix] 로그인 버그 해결

- src/pages/search/components/Calendar/index.css.ts
- src/pages/search/components/SearchBar/index.tsx
- close #300  
- 탐색페이지 enter키 눌렀을 때, 검색 가능하도록 수정
- 탐색페이지 캘린더 padding 수정
> [Fix] 탐색페이지 엔터시에도 검색 가능하도록 수정

- src/components/ClassCard/index.css.ts
- src/components/ClassCard/index.tsx
- src/pages/home/components/LessonItem/index.css.ts
> [Feat] classCard 장소 수정

- src/pages/home/components/LessonItem/index.css.ts
> [Fix] 글자 수 제한

- src/routes/router.tsx
- close #314 
클래스 개설 완료 페이지 route 추가
> [!HOTFIX] 클래스 개설 완료 페이지 route 추가

- src/pages/search/Search.tsx
- src/pages/search/apis/queries.ts
- src/pages/search/components/SearchBar/SearchBar.tsx
- src/pages/search/utils/searchHandlers.ts
- src/shared/hooks/useDebounce.ts
- src/shared/hooks/useDebounce.tsx
- close #332
- 검색 페이지 input 입력에 debounce를 적용했습니다. (useDebounce)
- search 페이지 내에서 사용되는 handle 함수들을 searchHandler 파일로 분리시켰습니다.
- 처음해보는 기능이라, 수정 필요한 부분 많이 코멘트 남겨주세요
- 기존 검색 페이지 방식: 글자 입력 후 엔터 또는 검색 아이콘 클릭시 결과가 보입니다.
- 변경 후: 사용자가 글씨를 입력한 후 0.5초 동안 입력이 없으면 클래스/댄서 정보를 요청하는 함수를 실행합니다. 아이콘 클릭/엔터 등의 이벤트가 없더라도 결과가 보입니다.
```ts
const useDebounce = ({ value, delay }: UseDebounceProps) => {
// input필드의 입력된 value의 디바운스된 값을 저장합니다.  초기값은 value로 설정됩니다.
const [debouncedValue, setDebouncedValue] = useState(value);
// setTimeout을 사용하여 value가 변경된 후 delay 시간이 지난 뒤에 debouncedValue를 업데이트합니다.
useEffect(() => {
const timerID = setTimeout(() => {
setDebouncedValue(value);
}, delay);
// clearTimeout은 컴포넌트가 언마운트되거나, value와 delay가 변경될 때 이전 타이머를 취소하여 불필요한 상태 업데이트를 방지합니다.
return () => {
clearTimeout(timerID);
};
}, …
```
> [Refactor] Search 페이지 Debounce 적용

- .github/workflows/chromatic.yml
- .github/workflows/cicd.yml
- .gitignore
- package.json
- pnpm-lock.yaml
- close #348 
- Chromatic을 이용해 스토리북 배포 진행했습니다. 
크로마틱에 가입 후, 만들어진 sopt-all 레포지토리에서 dash 레포를 연결했습니다. 
이때 발급되는 토큰을 dash 레포의 키로 추가해두었습니다.
그 후  전체적인 작업은 공식문서를 참고해서 진행했습니다.
https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/
다만 다른점은, yml 파일 작성시 저희는 pnpm을 사용하고 있기 때문에 pnpm 관련 의존성 및 패키지 설치 부분, 빌드 완료시 github-actions 코멘트 달아주기 입니다
봇 댓글 지저분한거 지송합니다아...
크로마틱은 스토리북에서 만든 전용 클라우드 배포 서버다.
storybook-static/은 정적 파일이기 때문에 ignore에 추가해 불필요한 용량 증가 및 버전 관리 혼란을 막는다
> [Feat] 스토리북 배포 자동화

- build.sh
- close #372 
레포 이전에 따른 auto sync workflow 설정 변경하였습니다.
build.sh의 레포명을 최신화 하였습니다.
> [Setting] 레포 이전에 따른 auto sync workflow 설정 변경

- src/pages/instructorRegister/components/InstructorRegisterFunnel/InstructorRegisterFunnel.tsx
> 이미지 최적화 확인 main 재반영 - build error 해결

- src/pages/home/components/MyPage/MyPage.tsx
- src/shared/types/myPageTypes.ts
> [!HOTFIX] role response 및 setRole 변경

- src/pages/instructorRegister/components/InstructorRegisterFunnel/InstructorRegisterFunnel.tsx
X
이미지 최적화 확인 main 재반영 - role response 수정
> 이미지 최적화 확인 main 재반영 - role response 수정

- src/pages/home/components/MyPage/MyPage.tsx
- src/pages/home/components/TopSection/TopSection.tsx
- close #382 
- roleData.role에서 roleData로 수정 ~~
> [Fix] 마이페이지 role 이름 수정

- src/pages/onboarding/Onboarding.tsx
- src/pages/onboarding/components/OnboardingHeader/OnboardingHeader.tsx
- src/pages/onboarding/components/OnboardingHeader/onboardingHeaderStyle.css.ts
- src/pages/onboarding/onboarding.css.ts
- close #406  
온보딩페이지 헤더 구현하였습니다.
> [Feat] Onboarding 헤더 구현 및 적용

- src/pages/instructorRegister/InstructorRegister.tsx
- src/pages/instructorRegister/components/VideoLinkSection/VideoLinkSection.tsx
- close #411 
강사 등록 페이지 유튜브 링크 해당 없음 적용했습니다.
> [Refactor] 강사 등록 페이지 유튜브 링크 해당 없음 적용

- src/pages/EditProfile/components/ProfileForm/ProfileForm.tsx
- src/pages/mypage/components/TabWrapper/components/TeacherContent/TeacherContent.tsx
- close #413 
- 강사 등록시 유투브, 인스타 그램 둘중 하나가 올때 로고/아이콘/가운데 점 안뜨게 처
> [Refactor] 유투브, 인스타 url 수정

- src/pages/instructorRegister/InstructorRegister.tsx
- src/pages/mypage/apis/queries.ts
- src/pages/mypage/components/TabWrapper/TabWrapper.tsx
- src/pages/mypage/components/TabWrapper/components/TeacherContent/TeacherContent.tsx
- src/pages/mypage/components/TabWrapper/components/TeacherContent/components/ToolTip/ToolTip.tsx
- src/pages/mypage/components/TabWrapper/components/TeacherContent/components/ToolTip/components/OverlayPage.tsx
- src/pages/mypage/components/TabWrapper/components/TeacherContent/components/ToolTip/components/overlayPage.css.ts
- src/pages/mypage/components/TabWrapper/components/TeacherContent/components/ToolTip/tooltip.css.ts
- src/pages/mypage/components/TabWrapper/components/TeacherContent/teacherContent.css.ts
- src/pages/mypage/components/TabWrapper/tabWrapper.css.ts
- src/pages/mypage/constants/storageKey.ts
- src/pages/mypage/utils/storage.ts
- src/shared/assets/svg/IcTriangle.tsx
- src/shared/assets/svg/IcXBlack.tsx
- close #404 
- 툴팁구현
- 클래스 개설 translate x
https://github.com/user-attachments/assets/cd0ddf7e-df65-413f-b5cb-d96e1d94e988
> [Feat] 마이페이지 툴팁 튜토리얼 구현

- src/pages/instructor/classRegister/ClassRegister.tsx
> 2차 스프린트 QA용 PROD 반영

- src/pages/instructor/classRegister/ClassRegister.tsx
- src/pages/instructor/classRegister/apis/queries.ts
- src/pages/instructorRegister/InstructorRegister.tsx
- src/pages/instructorRegister/components/CareerSection/CareerSection.tsx
- src/pages/search/Search.tsx
- src/shared/apis/queries.ts
- close #445 
1. 강사 등록/수정 관련 잘못 설정되어 있던 onSuccess를 변경
2. 강사 등록/수정 관련 invalidatequeries 적용
3. 검색 디바운스 시간 500ms에서 300ms로 변경
> [!HOTFIX] invalidatequeries및 검색 디바운스 시간 변경

- src/pages/home/components/Footer/Footer.tsx
- src/pages/home/components/LessonItem/LessonItem.tsx
- src/pages/home/components/LessonItem/lessonItem.css.ts
- src/pages/mypage/components/TabWrapper/components/TeacherContent/components/ToolTip/ToolTip.tsx
- src/shared/utils/dateCalculate.ts
- close #452
qa 사항 반영했습니다! 
commit 별로 보는걸 추천 드립니다!
툴팁 있을시에 스크롤을 막아야해서 useEffect로 구현해주었습니다!
```ts
useEffect(() => {
document.body.style.overflow = 'hidden';
return () => {
document.body.style.overflow = 'auto';
};
}, []);
```
> [Refactor] sp2 마이페이지-강사 / 홈 추가 qa사항 반영

- src/pages/mypage/components/mypageReservation/MypageReservation.tsx
- src/shared/components/ClassCard/ClassCard.tsx
- close #463
클래스 카드 컴포넌트  div에 누락되어있는  flexDirection column 추가 했습니다 !
> [design] 클래스 신청 내역 페이지 내 flexDirection 추가

- .storybook/preview.tsx
- public/svg/ic_clear_alert_20.svg
- public/svg/ic_clear_gray09_20.svg
- public/svg/ic_clear_main03_20.svg
- public/svg/ic_meatball_alert_20.svg
- public/svg/ic_meatball_main03_20.svg
- src/shared/assets/svg/IcClearAlert20.tsx
- src/shared/assets/svg/IcClearGray0920.tsx
- src/shared/assets/svg/IcClearMain0320.tsx
- src/shared/assets/svg/IcMeatballAlert20.tsx
- src/shared/assets/svg/IcMeatballMain0320.tsx
- src/shared/components/ClassCard/ClassCard.tsx
- src/shared/components/ClassCard/classCard.css.ts
- src/stories/ClassCard.stories.tsx
- close #486 
- class card 뷰 변경
- storybook queryClient 설정
스토리북으로 뷰 확인해주세요!
> [Feat] class card 변경사항 반영

- src/common/components/Dropdown/style.css.ts
- src/pages/mypage/components/mypageCancelClass/MypageCancelClass.tsx
- src/pages/mypage/components/mypageReservation/components/ReservationList.tsx
- src/pages/mypage/utils/clickUtils.ts
- src/shared/constants/apiURL.ts
- close #519 
- `ClassCard` -> `ReservationList`로 변환
- 특정 예약 ID가 제공된 경우 해당 예약만 필터링하여서 `ClassConfirmPage`에 띄워주기
- 기타 빌드 에러 해결
https://github.com/user-attachments/assets/10642cc8-c7c4-4254-b3b1-707a58113848
> [Feat] 클래스 수강 목록 취소하기 로직 연결

- src/pages/accountRegister/AccountRegister.tsx
- src/pages/accountRegister/accountRegister.css.ts
- src/pages/accountRegister/apis/axios.ts
- src/pages/accountRegister/apis/queries.ts
- src/pages/accountRegister/types/api.ts
- src/pages/instructor/lessonManage/LessonManage.tsx
- src/pages/instructorRegister/apis/axios.ts
- src/shared/constants/apiURL.ts
- src/shared/constants/queryKey.ts
- close #526 
- 선생 계좌 등록/수정 API 연결
- 선생 계좌 조회 API 연결 (수정용)
큰 PR Point는 없습니다!
> [Feat] 계좌 등록/수정 API 연결 (+은행 목록 API)

- src/pages/instructor/classDetail/components/StudentCard/StudentCard.tsx
- src/pages/mypage/components/mypageReservation/components/ReservationList.tsx
- src/pages/mypage/components/mypageReservationDetail/MypageReservationDetail.tsx
- src/pages/mypage/components/mypageReservationDetail/types/api.ts
- src/shared/utils/timeUtils.ts
- close #540
- 수강상태 변경 버튼 연타 방지
- 취소상태시 클래스 카드에서 취소하기 버튼 없애기
> [Refactor] 개발 qa - 규홍

- src/pages/mypage/components/CancelConfirmPage/CancelConfirmPage.tsx
- src/pages/mypage/components/CancelConfirmPage/cancelConfirmPage.css.ts
- src/pages/mypage/components/CancelConfirmPage/components/RefundAccountSection/refundAccountSection.css.ts
- src/pages/mypage/components/CancelConfirmPage/components/RefundPolicySection/RefundPolicySection.tsx
- src/pages/mypage/components/CancelConfirmPage/components/RefundPolicySection/refundPolicySection.css.ts
- src/shared/components/BlurButton/BlurButton.css.ts
- src/shared/components/BlurButton/BlurButton.tsx
- close #553 
- [바텀시트 아래 뜨는 "다음" 버튼 zindex 조정](https://www.notion.so/SP3-QA-2734ce04a7c680a2a77ff78e2374d860?p=2744ce04a7c680c7acb5cc753d5f0473&pm=s)
- [취소 및 환불 약관 안내 백그라운드 컬러](https://www.notion.so/SP3-QA-2734ce04a7c680a2a77ff78e2374d860?p=2744ce04a7c6807ebd8dffbac6b42b3f&pm=s)
- [클래스 취소 신청자/클래스 정보 확인에서 여백](https://www.notion.so/SP3-QA-2734ce04a7c680a2a77ff78e2374d860?p=2744ce04a7c6802cb4a5ea07cc545850&pm=s)
> [Fix] sp3 전체 QA 반영

- src/pages/accountRegister/AccountRegister.tsx
- src/shared/hooks/useImageUploader.ts
- close #541 
- account register에서 은행 field invalidate query 추가
- image upload 예외 처리 추가
크게 복잡한 작업은 없고 계좌 등록에서 은행 부분 `invalidate` 로직 추가했고, 이미지 업로드 하는 부분 전체적인 예외처리로 `toast` 뜨드록 공통 hook인 `useImageUploader`에 처리했어요.
> [Fix] sp3 개발 QA 수정 반영 (계좌, 이미지 등록 예외처리)
