src/styles/theme.css.ts

- close #29 
font 명을 쉽게 바꾸었습니다!
앞으로 작업하실때 피그마에서 아래 사진에서 보이는것처럼 b2 글자만 보고 `vars.fonts.b2` 만 입력하면 폰트가 적용됩니다!

[Style] font명 단순화

---

src/components/Head/index.css.ts
src/components/Head/index.tsx
src/stories/Head.stories.tsx

- close #22
Head 공통 컴포넌트를 구현했습니다!
h1 ~ h6 시멘틱 태그를 사용할때 사용하면 됩니다.
시멘틱 태그의 level과 폰트를 자유롭게 주입하기 위해 level, tag 두개의 prop을 받습니다.
- level: h1 ~ h6 의 시멘틱 태그 레벨을 의미
- tag: h1 ~ h7 의 폰트명을 의미
두 prop에 주입되는 값이 동일해서 헷갈릴수 있다고 생각하는데 더 좋은 네이밍이나 방향이 생각나면 알려주세요!
```typescript
<Head level='h1' tag='h2'>진혁이 바보</Head>
```
위의 코드는 h1 시멘틱 태그에 h2 폰트를 적용시킨 예시입니다.
스토리북 확인해주세요!

[Feat] Head 공통 컴포넌트 구현

---

src/hooks/useFunnel.tsx

- close #40 
Funnel 구조를 쉽게 사용하기 위해 useFunnel 커스텀 훅을 구현하였습니다.
- `useFunnel(totalSteps: number, completePath: string)`으로 정의되어 있습니다.
- `totalSteps` : 완료 페이지까지 funnel 구조의 step으로 생각한다.
- `completePath` : funnel 구조가 끝나고 (완료 후) 리다이렉션 할 페이지 path를 의미한다.
- useFunnel hook의 return 값은 3가지입니다.
- `Funnel` : 퍼널 구조에서 step을 감싸주는 역할
- `Step` : 퍼널 구조에서 단계를 나타내는 컴포넌트를 감싸주는 역할
- `setStep` : step을 이동하는 함수
- `setStep()`은 **-1 | 1**의 값을 줄 수 있다.
- `-1` : 이전 페이지 (만약 첫 step이라면 이전 페이지로 navigate 된다.)
- `1` : 다음 페이지 (만약 마지막 step이라면 `completePath`로 navigate 된다.)
1. Funnel 구조가 필요한 Page 컴포넌트에서 useFunnel hook으로 return 값을 받는다.
`const { Funnel, Step, setStep } = useFunnel(3, '/reservation'); // total step 개수, redirection 페이지 path
`
2. Funnel/Step을 활용해 필요한 step에 맞게 컴포넌트를 구조화한다.
```ts
<Funnel>
<Step name="1">
<StepOne/> …
```

[Feat] Funnel 구조 초기 세팅

---

src/components/Tag/index.css.ts
src/components/Tag/index.tsx
src/routes/router.tsx
src/stories/Tag.stories.tsx

- close #68 
- 탐색 페이지에서 사용되는 태그 컴포넌트의 스타일을 추가로 작성했습니다. storybook으로 확인 가능합니다.
```ts
<Tag type='search' size='large'>K-POP</Tag>
```
일단은 seach 페이지에서만 사용되는 것 같아서 type을 search로, 크기를 large로 설정해주시면 똑같이 만들어집니다!

[Feat] Tag 공통 컴포넌트 스타일 추가

---

package.json
pnpm-lock.yaml
src/components/BoxButton/index.tsx
src/components/Card/index.tsx
src/components/Divider/index.tsx
src/components/Flex/index.tsx
src/components/Head/index.tsx
src/components/Input/index.tsx
src/components/Tag/index.tsx
src/components/Text/index.tsx

- close #76
- clsx 라이브러리를 도입했습니다
- 현재 구현된 공통 컴포넌트 중 tab, header를 제외하고 clsx 라이브러리로 className을 병합시켜줬습니다.
바엑을 사용하면 하나의 컴포넌트에 여러개의 className을 지정하면 하나의 className만 적용됩니다. 따라서 만들어둔 컴포넌트에 새롭게 스타일을 주입하고 싶다면 여러개의 스타일 모듈을 병합해주는 작업을 거쳐야합니다. 이 과정을 쉽게 해주는 라이브러리로 clsx, classNames 두개의 라이브러리가 있습니다!
두 라이브러리 중 clsx 의 성능이 더 좋고 최근 clsx가 치고 올라오는 추세라 clsx를 도입하였습니다. 자세한 비교는 [아티클](https://ux.stories.pe.kr/344)에서 확인하시면 좋을것 같습니다!
사용 방법은 다음과 같습니다.
1. clsx import
2. className={clsx(className, tagStyle({ size, type }))} 로 해당 컴포넌트에서 설정하는 style과 className의 스타일을 병합해줍니다.
```typescript
import clsx from 'clsx';
import { ComponentPropsWithoutRef } from 'react';
import { tagStyle } from '@/components/Tag/index.css';
interface TagProps extends ComponentPropsWithoutRef<'div'> {
size: 'small' | 'medium' | 'thumbnail';
type: …
```

[Feat] clsx 라이브러리 도입

---

src/App.tsx
src/mocks/mockReservationData.ts
src/pages/mypage/mypageReservation/index.css.ts
src/pages/mypage/mypageReservation/index.tsx
src/routes/router.tsx
src/types/reservationTypes.ts

- close #88 
- ClassCard 공통 컴포넌트를 이용해서 클래스 예약 내역 조회 전체 페이지 레이아웃을 완성했습니다!!
- Card에 관련된 자세한 사항은 classCard PR과 동일하므로 자세한 내용은 생략하겠습니다! 안에 들어가는 내용은 mockReservationData를 이용해서 실제 api 반환값을 사용하는 것처럼 작성했습니다.
- 상단에 전체 3같은 경우에는 반환값의 length를 이용했습니다.
```ts
const totalReservation = MOCK_RESERVATION_DATA.reservations.length;
```

[Feat] 클래스 예약 내역 페이지 전체 레이아웃

---

src/pages/search/TabContainer/TagSection/BottomSheet/index.css.ts
src/pages/search/TabContainer/TagSection/BottomSheet/index.tsx
src/pages/search/TabContainer/TagSection/index.tsx
src/pages/search/TabContainer/index.tsx

- close #110 
- 탐색 페이지 바텀 시트 구현
- 탐색 페이지 바텀 시트 탭 컴포넌트 배치
```typescript
document.body.style.overflow = 'hidden';
```
바텀시트가 올라왔을 때, 뒷배경이 스크롤 되지 않도록 해당 코드 추가해 주었습니다.
https://github.com/user-attachments/assets/670c0b19-df4f-4b09-bfb1-d45b8b5979b2

[Feat] 탐색 페이지 바텀시트 구현

---

src/components/Header/index.tsx
src/hooks/useFunnel.tsx
src/pages/instructorRegister/index.tsx

- close #132  
Funnel 구조 첫 번째 step에서 이전 페이지 이동 안 되는 문제를 해결 하였습니다.
해당 문제를 해결하기 위해서는 근본적으로 Header 컴포넌트 이전 Back아이콘을 누르면 `useFunnel`의 `setStep()`함수를 실행하도록 해야하는데 기존의 Header컴포넌트에는 고정적으로 `navigate(-1)`이 있기 때문에 고민을 많이 하게 되었습니다.
이를 함수를 주입하도록 동적 분기 처리하면 이 문제는 해결되기는 하지만 이렇게 공통 컴포넌트를 제가 수정하면 다른 view에서 쓰는 Header를 모두 바꿔야 하는 문제가 생기는 것을 파악했습니다.
그래서 저는 이를 Funnel일 경우와 일반적인 경우를 분기 처리하도록 구현하였습니다. `optional`로 `onFunnelBackClick`를 주도록 하여 Funnel일 경우는 `setStep`함수를 전달하도록 분기 처리 하였습니다!
```ts
const BackIcon = ({ onFunnelBackClick }: BackIconProps): JSX.Element => {
const navigate = useNavigate();
const handleBackClick = () => {
// Funnel 구조에서는 이전 버튼 누를 시 setStep(-1)을 해준다.
if (onFunnelBackClick) {
onFunnelBackClick();
return;
}
navigate(-1);
};
//...
};
```
문제가 되는 플로우는 아래와 같습니다.
`step 1` -> (다음 버튼) -> `step 2` -> (다음 …

[Fix] Funnel 구조 첫 번째 step에서 이전 페이지 이동 안 되는 문제 해결

---

src/pages/search/components/TabContainer/TagSection/BottomSheet/index.css.ts
src/pages/search/components/TabContainer/TagSection/BottomSheet/index.tsx
src/pages/search/components/TabContainer/TagSection/index.tsx
src/pages/search/components/TabContainer/index.css.ts
src/pages/search/components/TabContainer/index.tsx

- close #155 
- keyframe 적용해주어 바텀시트 열리고 닫히는 애니메이션 적용해주었습니다.
- 탐색페이지 반응형시 width값 100% 먹히지 않는 이슈 해결했습니다.
https://github.com/user-attachments/assets/eb72a710-97a2-4337-af05-9419ac989f49

[Design] 탐색페이지 바텀시트 애니메이션 적용

---

src/apis/auth/axios/index.ts
src/apis/auth/quries/index.ts
src/apis/common/axios/index.ts
src/apis/common/queries/index.ts
src/pages/home/components/BottomSection/index.tsx
src/pages/home/components/MyPage/index.tsx
src/types/roleTypes.ts

- close #219 
- 토큰권한 API를 수정했습니다.
```ts
export interface RoleApiResponse {
role: string;
}
``` 
많이 졸렸었나.. 왜 전에 그렇게 적었었을까요...
또 role에 대한 값은 그 안 role에 있기 때문에
` const isInstructor = role?.role === 'TEACHER';` role?.role로 작성해주었더니 정상적으로 작동했습니다.
- 로그아웃 api를 연결했습니다. 로그아웃은 Auth라고 생각해 홈에서 사용되지만 auth 폴더에서 작성했습니다.
```ts
export const postLogout = async () => {
await instance.post(API_URL.AUTH_LOGOUT);
};
export const usePostLogout = () => {
return useMutation({
mutationFn: postLogout,
onSuccess: () => {
clearStorage();
window.location.reload();
},
onError: (error: AxiosError) => {
console.error('Logout failed:', error);
},
});
};
```
로그아웃 post에 대한 요청이 성공하면 로컬 스토리지에있는 액세스토큰과 리프레쉬 토큰을 지우고, 창을 리로드합니다. 처음에 navigate('/')으로 가게 했었는데, 생각해보니 마이페이지는 이미 홈 주소 위에 있는 컴포넌트라 navigate가 무소용... 이여서 …

[Api] 로그아웃 api 연결 및 토큰 권한 api 수정

---

src/apis/reservation/axios/index.ts
src/apis/reservation/queries/index.ts
src/components/Header/index.tsx
src/pages/mypage/mypageReservation/index.tsx
src/pages/reservation/components/TossPayments/CheckOut/CheckOut.tsx
src/pages/reservation/components/TossPayments/Success/Success.tsx
src/pages/reservation/components/TossPayments/index.css.ts
src/pages/reservation/index.tsx

- close #272  
- 토스페이먼츠 결제 api 연동
- 클래스 예약 내역에서 `<` 아이콘 클릭시 무조건 home으로 이동하도록 수정
- 클래스 신청 페이지에서 가격, 클래스명, 신청자 명, 결제 페이지로 넘겨주도록 수정 
https://github.com/user-attachments/assets/8a71b025-7aa0-493f-931a-fc092d024752
모바일로 결제 진행하면 토스 어플 열리기 때문에 자연스럽게 진행 될 겁니다!

[Feat] 토스페이먼츠 결제 api 연동

---

.storybook/preview.ts
src/shared/components/Input/Input.tsx
src/shared/components/Input/input.css.ts
src/shared/styles/global.css.ts
src/stories/Input.stories.tsx

- close #328 
공통 컴포넌트 Input의 focus가 제대로 유지되지 않는 문제를 해결하였습니다. 
추가로 Input의 storybook 코드를 작성하였습니다.
Input 공통 컴포넌트의 focus가 유지되지 않는 문제를 focus css 조건이 잘못되었다고 판단했고, 이를 수정하였습니다!
제가 구현해야 할 Input 공통 컴포넌트의 focus 조건은 다음과 같습니다.
1. 기본적으로 input에 focus하면 **main color**가 테두리에 적용된다. blur의 경우 이를 제거한다.
2. 값을 입력하는 경우에도 focus의 상태로 판단하므로 1번을 동일하게 적용한다.
3. blur인 경우에는 값이 있어도 border는 없어야 한다.
4. 유효성 검사 유무에 따라 조건 분기를 한다.
a. `유효성 검사가 있다면` - `isError`가 true라면 1번의 focus css는 무시되어야 한다. focus main color 대신 isError에 해당하는 **alert2(red) color**를 테두리 색으로 적용한다.
b. `유효성 검사가 없다면` - 1번 상황을 그대로 적용
**간단하게 요약하자면 값의 유무와 상관없이 focus 된 경우에는 border(main color)가 적용되어야 하고, props로 isError의 값이 true로 넘어올 경우 focus 유무와 관계없이 main color border를 무시하고, border(alert2)가 적용되어야 한다는 것입니다.** 
기존에는 해당 구현을 위해 아래와 같이 작성이 되어 있었습니다.
```ts
const hasValue = …
```

[Fix] Input 공통 컴포넌트 focus 문제 해결

---

src/pages/auth/auth.ts
src/pages/login/components/KakaoButton/KakaoButton.tsx

- close #342  
해당 작업은 매번 테스트 할 때마다 Kakao 소셜 로그인 Redirect URI를 바꿔야 하는 불편함으로부터 시작되었습니다.
QA 혹은 실제 배포 환경에서 잘 작동하는지 테스트를 하려면 `prod` 환경의 URI가 필요했고, 테스트 진행 후 다시 개발에 들어갈 때는 다시 `dev`환경의 URI를 바꾸는 과정이 불편하고 불필요한 리소스 낭비라고 생각했습니다.
또한 애초에 Redirect URI가 하드 코딩 되어 상수로 직접 지정하여 쓰는 것은 변경이 있을 때마다 여러 파일에 접근해 수정해야 하는 불편함도 있었으며, 노출할 필요도 없다고 생각했습니다.
따라서 이를 `env`파일에 환경 변수로 지정하여 사용하도록 변경하였습니다. 또한 각자 local 환경에서는 `env`에 `local` 환경 전용 URI를 쓰고 작업을 하고, 배포한 vercel에서 `local`과 `prod`환경을 분리하여 `env`가 적용되도록 설정하였습니다.
해당 방법은 vercel에서 2가지 환경을 구분하여 `env`를 적용하는 방법인데, 혹시나 이 방법 외에 좋은 방법이 있거나 해당 접근에 단점이 있다면 편하게 말해주시면 감사하겠습니다 :)

[Setting] Kakao Redirect URI env로 변경 & prod 환경 분리

---

src/layout/Layout.tsx
src/pages/mypage/mypageReservationDetail/MypageReservationDetail.tsx
src/routes/router.tsx

- close #337 
기존에는 페이지 이동 시 스크롤 위치를 그대로 유지하는 문제가 있었습니다. (하단 영상 참고)
그래서 검색페이지에서 수업들이 많이 등록되어있는 경우에, 직접 최상단으로 스크롤을 올려서 확인해야하는 UX를 저해하는 불편함이 있었습니다.
`React Router`는 기본적으로 페이지 전환 시 스크롤 위치를 그대로 유지한다고 해요.
즉, A페이지 → B페이지로 이동해도 window.scrollY가 300px이면 그 상태로 B 페이지가 렌더링됩니다.
이는 일반적인 SPA(Single Page Application)의 특징이기고 합니다. 페이지가 새로고침되지 않기 때문입니다.
`React Router`에서는 `ScrollRestoration`을 제공해주고 있습니다. 
`ScrollRestoration`은 페이지 전환 시 스크롤 위치를 자동으로 복원해주는 역할을 합니다.
```
브라우저 '뒤로 가기' / '앞으로 가기'를 할 때
→ 해당 페이지에 있던 스크롤 위치를 복원
일반적인 페이지 전환 시
→ 스크롤을 최상단으로 이동
```
**Layout.tsx**
```js
import { Outlet, ScrollRestoration } from 'react-router-dom';
const Layout = () => {
return (
<>
<Outlet />
<ScrollRestoration />
</>
);
};
export default Layout;
```
다음과 같이 `Layout.tsx`에 `<Outlet />`과 함께 `<ScrollRestoration />`을 구성해주었습니다. …

[Feat] 페이지 이동 시 스크롤 위치 항상 최상단에 고정시키기

---

src/pages/search/Search.tsx
src/pages/search/components/TabContainer/TabContainer.tsx
src/pages/search/constants/index.tsx
src/pages/search/hooks/useTabNavigation.ts

- close #427  
QA 사항 중, Search 페이지에서 "댄서" 탭에서 댄서 상세 페이지로 들어갔다가 다시 Search페이지로 돌아와도 "댄서" 탭이 클릭된 상태로 유지하게 해달라는 요청이 있었습니다.
기존에는 다음과 같이
`const [selectedTab, setSelectedTab] = useState(0);`
`selectedTab` 상태를 `TabContainer`컴포넌트 내부에서 정의하여 사용하고 있었기 때문에, 페이지를 떠났다가 돌아오면 상태가 초기화되고 있었습니다. 해당 문제를 해결하기위한 고민해본 해결 방안은 다음과 같습니다.
1. 로컬 스토리지 사용
2. Location State 사용
3. 전역 상태 활용
4. url 파라미터 활용
5. 상태 보존 라우팅
다섯가지 모두 장단점이 분명하게 존재하고, **url 파라미터**를 활용하는 방법을 최종으로 선택한 이유는 다음과 같습니다.
- `React Router`의 `useSearchParams` 훅을 사용하면 URL 파라미터를 쉽게 읽고 설정할 수 있습니다. 그래서 별도의 라이브러리를 도입하지 않고도 상태를 관리할 수 있습니다.
- URL 파라미터를 사용하면 페이지를 새로고침해도 상태가 유지됩니다. 이는 사용자가 예기치 않게 페이지를 새로고침하더라도 이전 상태를 그대로 복원할 수 있게 해줍니다.
- `클래스 탭` : `http://localhost:5173/search?tab=0`, `댄스 탭` : `http://localhost:5173/search?tab=1`
- 댄스 탭이 활성화된 상태의 URL을 복사하여 다른 사람에게 …

[Refactor] search 페이지 tab 상태관리 수정

---

src/pages/search/Search.tsx
src/pages/search/hooks/useTabNavigation.ts

- close #449
기존 검색페이지의 탭별 url 히스토리 스택 관련하여 탭간 이동이 발생해도 브라우저 히스토리에 쌓이도록 변경했습니다.
기존 코드에서는 탭간 이동이 발생해도 브라우저 히스토리에 쌓이지 않지만, 클래스 탭 -> 댄서 탭 -> 클래스 탭인 상황에서 뒤로가기를 2번해야 홈으로 돌아갈 수 있었습니다. 왜냐하면, 이미 방문했던 탭으로 다시 이동할 때 `replace: true` 옵션을 사용하여 현재 히스토리 항목을 대체하게 되는데 해당 부분에서 문제가 발생하게 됩니다.
클래스 탭 방문 → 히스토리 스택: [클래스 탭]
댄서 탭 방문 → 히스토리 스택: [클래스 탭, 댄서 탭]
클래스 탭 재방문(replace: true) → 히스토리 스택: [클래스 탭, 클래스 탭] (댄서 탭이 클래스 탭으로 대체됨)
뒤로가기 → 클래스 탭으로 이동 (원래는 댄서 탭이었지만 대체됨)
뒤로가기 → 홈으로 이동
해당문제를 해결하기위해서는 브라우저 히스토리를 조작하기 위해서 추가적인 useEffect 코드가 필요하게 되고(브라우저 히스토리 조작은 사이드 이펙트 이므로), 너무 극단적인 상황을 염두해두고 불필요한 사이드이펙트를 야기할 수 있다고 판단하였습니다. 그래서 기획과 논의하여 브라우저 히스토리를 조작하지 않는 방향으로 수정하도록 하였습니다.

[Fix] 검색 페이지 url 히스토리 수정

---

src/pages/editProfiles/components/FormField/FormField.tsx
src/pages/editProfiles/components/ProfileForm/ProfileForm.tsx
src/pages/editProfiles/constants/validationMessage.ts
src/pages/editProfiles/schema/profileSchema.ts
src/pages/editProfiles/utils/inputUtils.ts
src/pages/instructorRegister/InstructorRegister.tsx
src/pages/instructorRegister/components/ImageUploadSection/ImageUploadSection.tsx
src/pages/instructorRegister/instructorRegister.css.ts
src/pages/mypage/components/TabWrapper/components/StudentContent/StudentContent.tsx
src/pages/mypage/components/TabWrapper/components/StudentContent/studentContent.css.ts
src/shared/components/Input/Input.tsx

- close #442 
- 프로필 기본 이미지 png -> svg
- 내정보 수정 유효성 관련 피그마에 맞게 수정
- 내정보수정 전화번호 숫자만 입력할 수 있게 수정
- 텍스트 필드 focus 관련 문제 해결 
- 유효성 검사시 첫글자 인식 안되는거 해결
```ts
name: z.string().superRefine((val, ctx) => {
if (val.length === 0) {
ctx.addIssue({ code: 'custom', message: NAME_ERRORS.REQUIRED });
return;
}
if (!/^[a-zA-Z0-9ㄱ-ㅎㅏ-ㅣ가-힣]+$/.test(val)) {
ctx.addIssue({ code: 'custom', message: NAME_ERRORS.INVALID });
return;
}
if (val.length < MIN_NAME_LENGTH) {
ctx.addIssue({ code: 'custom', message: NAME_ERRORS.REQUIRED });
return;
}
if (val.length > MAX_NAME_LENGTH) {
ctx.addIssue({ code: 'custom', message: NAME_ERRORS.TOO_LONG });
return;
}
}),
```
닉네임이나 이름 입력 시, 최소 길이와 특수기호 및 공백에 대한 유효성 검사가 겹치면서 에러 메시지가 제대로 출력되지 않는 문제가 있었습니다.
예를 들어, 첫 글자가 띄어쓰기일 경우 이를 인식하지 못했고,
첫 글자가 한 글자만 입력된 경우에는 닉네임 최소 길이 에러 메시지만 …

[Refactor] 2차 QA 수정 반영

---

src/pages/editProfiles/components/FormField/FormField.tsx
src/pages/editProfiles/components/ProfileForm/ProfileForm.tsx
src/pages/instructor/classRegister/components/ClassAmount/ClassAmount.tsx
src/pages/instructor/classRegister/components/ClassName/ClassName.tsx
src/pages/instructor/classRegister/components/ClassPersonnel/ClassPersonnel.tsx
src/pages/onboarding/components/ProfileStep/ProfileStep.tsx
src/shared/components/Input/Input.tsx
src/shared/components/Input/input.css.ts

- close #466 
Input 공통 컴포넌트에서 `helperText` & `length` 로직을 내부로 추상화했어요.
이전부터 나온 문제였지만 조금 수정이 늦었습니다. 해당 작업 반영 전까지 Input 공통 컴포넌트를 사용할 때 다음과 같은 불편함이 있었어요.
1. 에러 상태에 따른 `helperText`(ex. error 메시지) 스타일 분기 처리 로직 작성 필요
2. 에러 상태에 따른 글자 수 스타일 분기 처리 로직 작성 필요
<br/>
<br/>
<br/>
쉽게 말해 위 사진처럼 `helperText`와 글자 수 text 모두 `default/error/focus` 등의 상태에 따라 스타일 분기가 되어야 했어요. 하지만 Input 공통 컴포넌트 내부에는 Input과 그 테두리만 포함된 상태로 구현이 되어있었기 때문에, 해당 2개의 상태 분기를 Input을 사용하는 모든 곳에서 다 정의해줘야 하는 불편함이 있었어요.
즉 `focus/blur`와 같은 상태 로직 등 동일한 로직을 매번 정의해야 하는 것이 문제였으니 반대로 이것을 중앙화해서 한 곳에서 관리하면 해결이 될 문제라고 생각했어요.
만약 text 스타일을 결정하는 상태가 input 테두리 색을 결정하는 상태와 다르게 작동해야 했다면 현재처럼 분리해서 사용하는 곳에서 해당 상태를 정의하는 것이 맞았겠지만, 동일했기 때문에 더욱더 수정하는 방향이 맞다고 판단했어요.
따라서 `defineInputState`와 `defineLengthState`함수로 상태를 결정하고 해당 상태를 recipe를 통해 스타일을 분기하도록 하였고, Input 내부에서 …

[Feat] Input helperText & length 로직 공통 컴포넌트 내부로 추상화 

---

src/pages/instructor/lessonManage/LessonManage.tsx
src/pages/onboarding/Onboarding.tsx
src/pages/onboarding/apis/axios.ts
src/pages/onboarding/apis/queries.ts
src/pages/onboarding/components/InfoStep/InfoStep.tsx
src/pages/onboarding/constants/index.ts
src/pages/onboarding/types/onboardInfoTypes.ts
src/shared/constants/apiURL.ts
src/shared/types/api.ts

- close #515
- 기본 온보딩 api에서 이름, 번호를 제외한 필드를 없앴어요
- 인증번호 전송 관련 api를 추가해서 연결했어요
- 에러코드에 관한 각각 토스트 처리가 달라서 status 코드와 메세지에 맞게 notify가 뜨도록 설정했어요
온보딩 과정의 휴대폰 인증 플로우를 완성하고, 다양한 예외 상황에 대한 사용자 피드백을 강화했습니다.
1. 인증 API 연동 및 상태 관리
usePostPhoneRequest와 usePostPhoneVerify 훅을 사용하여, '인증 요청' 및 '인증번호 확인' API를 연동했습니다.
isLoading 외에 requestCount 상태를 추가하여, 하루 5회까지만 인증을 요청할 수 있도록 비즈니스 로직을 구현했습니다.
2. 에러 핸들링
API 명세에 따라, onError 콜백 내에서 HTTP status 코드를 분기 처리하여 각 상황에 맞는 사용자 피드백을 제공하도록 구현했습니다.
- handleRequestVerification (인증번호 요청 시): 404 Not Found: "이미 등록된 전화번호에요"
- 기타 에러: "인증번호 전송에 실패했어요"
- handleVerifyCode (인증번호 확인 시): 409 Conflict: "인증번호가 일치하지 않아요"
- 400, 500 등 기타 서버 에러: 서버에서 전달된 에러 메시지를 그대로 토스트로 노출
3. 비즈니스 로직에 따른 예외 처리
API 에러 외에도, 사용자 경험을 해칠 수 있는 비즈니스 로직 상의 예외 케이스들을 아래와 같이 처리했습니다.
- 10초 이내 재요청 시: "잠시 후 다시 요청해주세요" …

[Feat] Onboarding 정보 전송 & 인증번호 전송 api 연결

---

src/pages/mypage/components/TabWrapper/components/TeacherContent/teacherContent.css.ts
src/pages/mypage/components/mypageReservationDetail/mypageReservationDetail.css.ts

- close #546 
- 기존에 아마 클래스 상세보기 페이지가 스크롤이 될만큼 세로 영역이 차있지 않은데, height: 100%를 주면 기존에서 헤더 영역만큼 아래로 스크롤이 되어서 높이를 `height: 'calc(100dvh - 6rem)',` 다음과 같이 주고 있었었는데, 이제 스크롤이 되어야 해서 다시 100%로 고쳤습니다.
- 마이페이지 - 강사 탭 내 클래스 개설 플로팅 버튼 fixed로 변경했습니다. 그리고 디바이스 화면이 아닐때도 정확한 위치에 뜨기 위해서 right를 전체 뷰에서 max-width 만큼 빠지게 계산해서 추가했습니다.

[Design] 클래스 상세보기 레이아웃 수정, 클래스 개설 플로팅 버튼 수정

---

src/pages/home/components/LessonItem/LessonItem.tsx
src/pages/home/constants/index.tsx

- close #544 
- 기존에는 마감 기한 지난 클래스 들도 d-day로 표시가 되는 오류가 있었어요.  서버에서 -7과 같은 음수로 remainingDays를 내려주고 있는데, 음수에 대한 처리는 안되어 있었어요. 따라서 남은 일수가 0이상 이고, 4일 미만 일때만 Tag가 노출되게 수정했습니다. 
```ts
{remainingDays < 4 && **_remainingDays >= 0_** && (
<Tag type="deadline" size="thumbnail" className={styles.deadlineTag}>
{calculateRemainingDate(startDate, remainingDays)}
</Tag>
)}
```
- 한줄 수정이라.. 리뷰 빠르게 부탁드려요 ㅎㅎ

[Fix] 마감 기한 지난 클래스 Tag 컴포넌트 비노출처리
